id: A721AEA5B
base_file: f6BA1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:03:07.871467
  last_modified_at: 2022-06-05 20:03:07.871475
